# Generated by Django 4.2.30 on 2026-06-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_feature_phone',
            field=models.BooleanField(default=False, help_text='If True, the system will automatically send SMS fallback vouchers to this user.'),
        ),
    ]
