# Generated by Django 4.2.30 on 2026-06-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_feature_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved_wholesaler',
            field=models.BooleanField(default=False, help_text='Designates whether the admin has verified and approved this wholesaler to redeem vouchers.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_wholesaler',
            field=models.BooleanField(default=False, help_text='Designates whether this user operates as a wholesaler.'),
        ),
    ]
