# Generated by Django 4.2.30 on 2026-06-18 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import payments.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pools', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRVoucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('fallback_code', models.CharField(default=payments.models.generate_fallback_code, max_length=12, unique=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('REDEEMED', 'Redeemed'), ('EXPIRED', 'Expired')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=payments.models.default_expiry)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='pools.pool')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
